# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wbsy3.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(678, 284)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(430, 30, 221, 231))
        self.groupBox_3.setObjectName("groupBox_3")
        self.over = QtWidgets.QPushButton(self.groupBox_3)
        self.over.setGeometry(QtCore.QRect(60, 150, 93, 28))
        self.over.setObjectName("over")
        self.begin = QtWidgets.QPushButton(self.groupBox_3)
        self.begin.setGeometry(QtCore.QRect(60, 110, 93, 28))
        self.begin.setObjectName("begin")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(170, 60, 51, 16))
        self.label_2.setObjectName("label_2")
        self.f = QtWidgets.QLineEdit(self.groupBox_3)
        self.f.setGeometry(QtCore.QRect(50, 60, 113, 21))
        self.f.setObjectName("f")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 30, 391, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 131, 71))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 261, 20))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 211, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 121, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 190, 181, 16))
        self.label_12.setObjectName("label_12")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(240, 30, 141, 141))
        self.graphicsView_2.setStyleSheet("background-image:url(\"D:Kaiming_He.png\")")
        self.graphicsView_2.setObjectName("graphicsView_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_3.setTitle(_translate("Dialog", "Please Select Frequency"))
        self.over.setText(_translate("Dialog", "End"))
        self.begin.setText(_translate("Dialog", "Run"))
        self.label_2.setText(_translate("Dialog", "GHz"))
        self.groupBox_2.setTitle(_translate("Dialog", "About me"))
        self.label_5.setText(_translate("Dialog", "Kilian Di 常迪 "))
        self.label_8.setText(_translate("Dialog", "Research Assistant@IIAU-Lab"))
        self.label_10.setText(_translate("Dialog", "2862588711cd@gmail.com"))
        self.label_11.setText(_translate("Dialog", "Intern@HKUST"))
        self.label_12.setText(_translate("Dialog", "Prof.Xu\'s Vision Group"))
